DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
    SAMPLER:
      RandomSampler
  TEST:
    BATCH_SIZE: 1
    
  NUM_WORKERS: 0

DATASET:
  NAME: ImageNetS

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["gaussian_noise", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.02
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 10

TEST:
  FINAL_MODEL: "best_val"

TRAINER:
  BATSTYLER: 
    WEIGHT_PATH: "/home/xuxiusheng/deeplearning/weights/"
    COARSESEMANTICSET: "batstyler/semantics/imagenets_new.txt"
    CLASSDIR: "batstyler/semantics/imagenets.txt"
    N_STYLES: 100
    STYLE_BATCH: 100
    EPS: 1e-7
    S: 5.0
    M: 0.5